name: Build and push
on:
  pull_request:
    branches:
      - main
  push:
    tags:        
      - '*'

jobs:
  build-image:
    strategy:
      matrix:
        include:
          - os: ubuntu-24.04
            arch: linux/amd64
            file-suffix: amd64
          - os: ubuntu-24.04-arm
            arch: linux/arm64
            file-suffix: arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/dcasado/que-me-falta
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}-${{ matrix.file-suffix }}
            type=semver,pattern={{major}}.{{minor}}-${{ matrix.file-suffix }}
            type=semver,pattern={{major}}-${{ matrix.file-suffix }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker images
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  push-images:
    needs: [build-image]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-24.04
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/dcasado/que-me-falta
          # generate Docker tags based on the following events/attributes
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Create manifest
        run: |
          docker manifest create ghcr.io/dcasado/que-me-falta:latest ghcr.io/dcasado/que-me-falta:latest-amd64 ghcr.io/dcasado/que-me-falta:latest-arm64
          docker manifest create ghcr.io/dcasado/que-me-falta:{{version}} ghcr.io/dcasado/que-me-falta:{{version}}-amd64 ghcr.io/dcasado/que-me-falta:{{version}}-arm64
          docker manifest create ghcr.io/dcasado/que-me-falta:{{major}}.{{minor}} ghcr.io/dcasado/que-me-falta:{{major}}.{{minor}}-amd64 ghcr.io/dcasado/que-me-falta:{{major}}.{{minor}}-arm64
          docker manifest create ghcr.io/dcasado/que-me-falta:{{major}} ghcr.io/dcasado/que-me-falta:{{major}}-amd64 ghcr.io/dcasado/que-me-falta:{{major}}-arm64

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create manifest
        run: |
          docker manifest push ghcr.io/dcasado/que-me-falta:latest
          docker manifest push ghcr.io/dcasado/que-me-falta:{{version}}
          docker manifest push ghcr.io/dcasado/que-me-falta:{{major}}.{{minor}}
          docker manifest push ghcr.io/dcasado/que-me-falta:{{major}}
